const types = {
    SHOP_SCHOOL_REQUEST_CLASSCARDS: "SHOP_SCHOOL_REQUEST_CLASSCARDS",
    SHOP_SCHOOL_RECEIVE_CLASSCARDS: "SHOP_SCHOOL_RECEIVE_CLASSCARDS",
    SHOP_SCHOOL_SET_CLASSCARDS_LOADED: "SHOP_SCHOOL_SET_CLASSCARDS_LOADED",
    SHOP_SCHOOL_SET_CLASSCARDS_LOADING: "SHOP_SCHOOL_SET_CLASSCARDS_LOADING",
}

export default types