const types = {
    CLASSES_REQUEST_CLASSES: "CLASSES_REQUEST_CLASSES",
    CLASSES_RECEIVE_CLASSES: "CLASSES_RECEIVE_CLASSES",
    CLASSES_SET_CLASSES_LOADED: "CLASSES_SET_CLASSES_LOADED",
    CLASSES_SET_CLASSES_LOADING: "CLASSES_SET_CLASSES_LOADING",
}

export default types