const types = {
    CHECKIN_REQUEST_REVENUE: "CHECKIN_REQUEST_REVENUE",
    CHECKIN_RECEIVE_REVENUE: "CHECKIN_RECEIVE_REVENUE",
    CHECKIN_REQUEST_TEACHER_PAYMENT: "CHECKIN_REQUEST_TEACHER_PAYMENT",
    CHECKIN_RECEIVE_TEACHER_PAYMENT: "CHECKIN_RECEIVE_TEACHER_PAYMENT",
    CHECKIN_REQUEST_VERIFY_TEACHER_PAYMENT: "CHECKIN_REQUEST_VERIFY_TEACHER_PAYMENT",
    CHECKIN_RECEIVE_VERIFY_TEACHER_PAYMENT: "CHECKIN_RECEIVE_VERIFY_TEACHER_PAYMENT",
    CHECKIN_SET_REVENUE_LOADED: "CHECKIN_SET_REVENUE_LOADED",
    CHECKIN_SET_REVENUE_LOADING: "CHECKIN_SET_REVENUE_LOADING",
    
}

export default types