const types = {
    CHECKIN_REQUEST_REVENUE: "CHECKIN_REQUEST_REVENUE",
    CHECKIN_RECEIVE_REVENUE: "CHECKIN_RECEIVE_REVENUE",
    CHECKIN_SET_REVENUE_LOADED: "CHECKIN_SET_REVENUE_LOADED",
    CHECKIN_SET_REVENUE_LOADING: "CHECKIN_SET_REVENUE_LOADING",
}

export default types