const api_urls = {
    'APP_PAYMENT_METHODS': '/pos/get_payment_methods.json',
    'APP_USER': '/pos/get_user.json',
    'APP_USER_LOGGED_IN': '/pos/get_logged_in.json',
    'APP_SETTINGS': '/pos/get_settings.json',
    'APP_VALIDATE_CART': '/pos/validate_cart.json',
    'CHECKIN_CLASSES': '/pos/get_classes.json',
    'CHECKIN_ATTENDANCE': '/pos/get_class_attendance.json',
    'CHECKIN_ATTENDANCE_UPDATE': '/pos/update_class_attendance.json',
    'CHECKIN_ATTENDANCE_DELETE': '/pos/delete_class_attendance.json',
    'CHECKIN_BOOKING_OPTIONS': '/pos/get_class_booking_options.json',
    'CHECKIN_BOOKING_CREATE': '/pos/customer_class_booking_create.json',
    'CHECKIN_BOOKING_MANAGE': '/pos/customer_class_booking_manage.json',
    'CHECKIN_REVENUE': '/pos/get_class_revenue.json',
    'CHECKIN_TEACHER_PAYMENT': '/pos/get_class_teacher_payment.json',
    'CHECKIN_VERIFY_TEACHER_PAYMENT': '/pos/verify_teacher_payment.json',
    'CUSTOMERS': '/pos/get_customers.json',
    'CUSTOMERS_SUBSCRIPTIONS': '/pos/get_customers_subscriptions.json',
    'CUSTOMERS_MEMBERSHIPS': '/pos/get_customers_memberships.json',
    'CUSTOMERS_MEMBERSHIPS_TODAY': '/pos/get_customers_memberships_today.json',
    'CUSTOMER_CREATE': '/pos/create_customer.json',
    'CUSTOMER_UPDATE': '/pos/update_customer.json',
    'CUSTOMER_PICTURE_UPDATE': '/pos/update_customer_picture.json',
    'SHOP_PRODUCTS': '/pos/get_products.json',
    'SHOP_PRODUCT_CATEGORIES': '/pos/get_product_categories.json',
    'SHOP_SCHOOL_CLASSCARDS': '/pos/get_school_classcards.json',
    'SHOP_SCHOOL_MEMBERSHIPS': '/pos/get_school_memberships.json',
    'SHOP_SCHOOL_SUBSCRIPTIONS': '/pos/get_school_subscriptions.json',
}

export default api_urls