const api_urls = {
    'APP_PAYMENT_METHODS': '/pos/get_payment_methods.json',
    'APP_TAX_RATES': '/pos/get_tax_rates.json',
    'APP_USER': '/pos/get_user.json',
    'APP_USER_LOGGED_IN': '/pos/get_logged_in.json',
    'APP_SETTINGS': '/pos/get_settings.json',
    'APP_VALIDATE_CART': '/pos/validate_cart.json',
    'CASH_COUNTS': '/pos/get_cash_counts.json',
    'CASH_COUNT_SET': '/pos/set_cash_count.json',
    'CLASSES_CLASSES': '/pos/get_classes.json',
    'CLASSES_ATTENDANCE': '/pos/get_class_attendance.json',
    'CLASSES_ATTENDANCE_UPDATE': '/pos/update_class_attendance.json',
    'CLASSES_ATTENDANCE_DELETE': '/pos/delete_class_attendance.json',
    'CLASSES_BOOKING_OPTIONS': '/pos/get_class_booking_options.json',
    'CLASSES_BOOKING_CREATE': '/pos/customer_class_booking_create.json',
    'CLASSES_BOOKING_MANAGE': '/pos/customer_class_booking_manage.json',
    'CLASSES_REVENUE': '/pos/get_class_revenue.json',
    'CLASSES_TEACHER_PAYMENT': '/pos/get_class_teacher_payment.json',
    'CLASSES_VERIFY_TEACHER_PAYMENT': '/pos/verify_teacher_payment.json',
    'CUSTOMERS': '/pos/get_customers.json',
    'CUSTOMER_CLASSCARDS': '/pos/get_customer_classcards.json',
    'CUSTOMER_SUBSCRIPTIONS': '/pos/get_customer_subscriptions.json',
    'CUSTOMERS_MEMBERSHIPS': '/pos/get_customers_memberships.json',
    'CUSTOMER_MEMBERSHIPS_TODAY': '/pos/get_customer_memberships_today.json',
    'CUSTOMER_CREATE': '/pos/create_customer.json',
    'CUSTOMER_UPDATE': '/pos/update_customer.json',
    'CUSTOMER_PICTURE_UPDATE': '/pos/update_customer_picture.json',
    'CUSTOMER_NOTES': '/pos/get_customer_notes.json',
    'CUSTOMER_CREATE_NOTE': '/pos/create_customer_note.json',
    'CUSTOMER_UPDATE_NOTE': '/pos/update_customer_note.json',
    'CUSTOMER_UPDATE_NOTE_STATUS': '/pos/update_customer_note_status.json',
    'CUSTOMER_DELETE_NOTE': '/pos/delete_customer_note.json',
    'EXPENSES': '/pos/get_expenses.json',
    'EXPENSE_CREATE': '/pos/create_expense.json',
    'EXPENSE_UPDATE': '/pos/update_expense.json',
    'EXPENSE_DELETE': '/pos/delete_expense.json',
    'SHOP_PRODUCTS': '/pos/get_products.json',
    'SHOP_PRODUCT_CATEGORIES': '/pos/get_product_categories.json',
    'SHOP_SCHOOL_CLASSCARDS': '/pos/get_school_classcards.json',
    'SHOP_SCHOOL_MEMBERSHIPS': '/pos/get_school_memberships.json',
    'SHOP_SCHOOL_SUBSCRIPTIONS': '/pos/get_school_subscriptions.json',
}

export default api_urls