const types = {
    REQUEST_CUSTOMERS: "REQUEST_CUSTOMERS",
    RECEIVE_CUSTOMERS: "RECEIVE_CUSTOMERS",
    REQUEST_CUSTOMERS_MEMBERSHIPS: "REQUEST_CUSTOMERS_MEMBERSHIPS",
    RECEIVE_CUSTOMERS_MEMBERSHIPS: "RECEIVE_CUSTOMERS_MEMBERSHIPS",
    SET_SEARCH_TIMEOUT: "SET_SEARCH_TIMEOUT",
    CLEAR_SEARCH_TIMEOUT: "CLEAR_SEARCH_TIMEOUT",
    // CHECKIN_SET_CLASS_ATTENDANCE_LOADED: "CHECKIN_SET_CLASS_ATTENDANCE_LOADED",
    // CHECKIN_SET_CLASS_ATTENDANCE_LOADING: "CHECKIN_SET_CLASS_ATTENDANCE_LOADING",
    // CHECKIN_SET_CLASS_ATTENDANCE_SEARCH_CUSTOMER_ID: "CHECKIN_SET_CLASS_ATTENDANACE_SEARCH_CUSTOMER_ID",
    // CHECKIN_SET_SEARCH_TIMEOUT: "CHECKIN_SET_SEARCH_TIMEOUT",
    // CHECKIN_CLEAR_SEARCH_TIMEOUT: "CHECKIN_CLEAR_SEARCH_TIMEOUT",
}

export default types