const types = {
    CLASSES_REQUEST_REVENUE: "CLASSES_REQUEST_REVENUE",
    CLASSES_RECEIVE_REVENUE: "CLASSES_RECEIVE_REVENUE",
    CLASSES_REQUEST_TEACHER_PAYMENT: "CLASSES_REQUEST_TEACHER_PAYMENT",
    CLASSES_RECEIVE_TEACHER_PAYMENT: "CLASSES_RECEIVE_TEACHER_PAYMENT",
    CLASSES_REQUEST_VERIFY_TEACHER_PAYMENT: "CLASSES_REQUEST_VERIFY_TEACHER_PAYMENT",
    CLASSES_RECEIVE_VERIFY_TEACHER_PAYMENT: "CLASSES_RECEIVE_VERIFY_TEACHER_PAYMENT",
    CLASSES_SET_REVENUE_LOADED: "CLASSES_SET_REVENUE_LOADED",
    CLASSES_SET_REVENUE_LOADING: "CLASSES_SET_REVENUE_LOADING",
    
}

export default types