const types = {
    REQUEST_EXPENSES: "REQUEST_EXPENSES",
    RECEIVE_EXPENSES: "RECEIVE_EXPENSES",
    REQUEST_CREATE_EXPENSE: "REQUEST_CREATE_EXPENSE",
    RECEIVE_CREATE_EXPENSE: "RECEIVE_CREATE_EXPENSE",
    REQUEST_UPDATE_EXPENSE: "REQUEST_CREATE_EXPENSE",
    RECEIVE_UPDATE_EXPENSE: "RECEIVE_CREATE_EXPENSE",
    REQUEST_DELETE_EXPENSE: "REQUEST_DELETE_EXPENSE",
    RECEIVE_DELETE_EXPENSE: "REQUEST_DELETE_EXPENSE",
    REQUEST_CASH_COUNTS: "REQUEST_CASH_COUNTS",
    RECEIVE_CASH_COUNTS: "RECEIVE_CASH_COUNTS"
}

export default types