const types = {
    REQUEST_EXPENSES: "REQUEST_EXPENSES",
    RECEIVE_EXPENSES: "RECEIVE_EXPENSES",
    REQUEST_CREATE_EXPENSE: "REQUEST_CREATE_EXPENSE",
    RECEIVE_CREATE_EXPENSE: "RECEIVE_CREATE_EXPENSE",
    REQUEST_UPDATE_EXPENSE: "REQUEST_CREATE_EXPENSE",
    RECEIVE_UPDATE_EXPENSE: "RECEIVE_CREATE_EXPENSE",
    REQUEST_DELETE_EXPENSE: "REQUEST_DELETE_EXPENSE",
    RECEIVE_DELETE_EXPENSE: "REQUEST_DELETE_EXPENSE",
    REQUEST_BALANCE: "REQUEST_BALANCE",
    RECEIVE_BALANCE: "RECEIVE_BALANCE"
}

export default types