const types = {
    REQUEST_CUSTOMER_MEMBERSHIPS_TODAY: "REQUEST_CUSTOMER_MEMBERSHIPS_TODAY",
    RECEIVE_CUSTOMER_MEMBERSHIPS_TODAY: "RECEIVE_CUSTOMER_MEMBERSHIPS_TODAY",
    CLEAR_CUSTOMER_MEMBERSHIPS_TODAY: "CLEAR_CUSTOMER_MEMBERSHIPS_TODAY"
}

export default types