const types = {
    REQUEST_NOTES: "REQUEST_NOTES",
    RECEIVE_NOTES: "RECEIVE_NOTES",
    REQUEST_CREATE_NOTE: "REQUEST_CREATE_NOTE",
    RECEIVE_CREATE_NOTE: "RECEIVE_CREATE_NOTE",
    REQUEST_UPDATE_NOTE: "REQUEST_UPDATE_NOTE",
    RECEIVE_UPDATE_NOTE: "RECEIVE_UPDATE_NOTE",
    REQUEST_UPDATE_NOTE_STATUS: "REQUEST_UPDATE_NOTE_STATUS",
    RECEIVE_UPDATE_NOTE_STATUS: "RECEIVE_UPDATE_NOTE_STATUS",
    REQUEST_DELETE_NOTE: "REQUEST_DELETE_NOTE",
    RECEIVE_DELETE_NOTE: "RECEIVE_DELETE_NOTE",
}

export default types