const types = {
    CLASSES_REQUEST_CLASS_ATTENDANCE: "CLASSES_REQUEST_CLASS_ATTENDANCE",
    CLASSES_RECEIVE_CLASS_ATTENDANCE: "CLASSES_RECEIVE_CLASS_ATTENDANCE",
    CLASSES_CLASS_ATTENDANCE_REQUEST_UPDATE_STATUS: "CLASSES_CLASS_ATTENDANCE_REQUEST_UPDATE_STATUS",
    CLASSES_CLASS_ATTENDANCE_RECEIVE_UPDATE_STATUS: "CLASSES_CLASS_ATTENDANCE_RECEIVE_UPDATE_STATUS",
    CLASSES_CLASS_ATTENDANCE_REQUEST_DELETE: "CLASSES_CLASS_ATTENDANCE_REQUEST_DELETE",
    CLASSES_CLASS_ATTENDANCE_RECEIVE_DELETE: "CLASSES_CLASS_ATTENDANCE_RECEIVE_DELETE",
    CLASSES_SET_CLASS_ATTENDANCE_LOADED: "CLASSES_SET_CLASS_ATTENDANCE_LOADED",
    CLASSES_SET_CLASS_ATTENDANCE_LOADING: "CLASSES_SET_CLASS_ATTENDANCE_LOADING",
    CLASSES_SET_CLASS_ATTENDANCE_SEARCH_CUSTOMER_ID: "CLASSES_SET_CLASS_ATTENDANACE_SEARCH_CUSTOMER_ID",
    CLASSES_ATTENDANCE_CLEAR_SEARCH_CUSTOMER_ID: "CLASSES_ATTENDANCE_CLEAR_SEARCH_CUSTOMER_ID",
    CLASSES_ATTENDANCE_SET_SEARCH_CUSTOMER_ID: "CLASSES_ATTENDANCE_SET_SEARCH_CUSTOMER_ID",
    CLASSES_ATTENDANCE_CLEAR_SEARCH_VALUE: "CLASSES_ATTENDANCE_CLEAR_SEARCH_VALUE",
    CLASSES_ATTENDANCE_SET_SEARCH_VALUE: "CLASSES_ATTENDANCE_SET_SEARCH_VALUE",
    CLASSES_ATTENDANCE_SET_SEARCH_TIMEOUT: "CLASSES_ATTENDANCE_SET_SEARCH_TIMEOUT",
    CLASSES_ATTENDANCE_CLEAR_SEARCH_TIMEOUT: "CLASSES_ATTENDANCE_CLEAR_SEARCH_TIMEOUT"
}

export default types