const types = {
    SHOP_SCHOOL_REQUEST_SUBSCRIPTIONS: "SHOP_SCHOOL_REQUEST_SUBSCRIPTIONS",
    SHOP_SCHOOL_RECEIVE_SUBSCRIPTIONS: "SHOP_SCHOOL_RECEIVE_SUBSCRIPTIONS",
    SHOP_SCHOOL_SET_SUBSCRIPTIONS_LOADED: "SHOP_SCHOOL_SET_SUBSCRIPTIONS_LOADED",
    SHOP_SCHOOL_SET_SUBSCRIPTIONS_LOADING: "SHOP_SCHOOL_SET_SUBSCRIPTIONS_LOADING",
}

export default types