const types = {
    SHOP_SCHOOL_REQUEST_MEMBERSHIPS: "SHOP_SCHOOL_REQUEST_MEMBERSHIPS",
    SHOP_SCHOOL_RECEIVE_MEMBERSHIPS: "SHOP_SCHOOL_RECEIVE_MEMBERSHIPS",
    SHOP_SCHOOL_SET_MEMBERSHIPS_LOADED: "SHOP_SCHOOL_SET_MEMBERSHIPS_LOADED",
    SHOP_SCHOOL_SET_MEMBERSHIPS_LOADING: "SHOP_SCHOOL_SET_MEMBERSHIPS_LOADING",
}

export default types