const types = {
    CLASSES_REQUEST_BOOKING_OPTIONS: "CLASSES_REQUEST_BOOKING_OPTIONS",
    CLASSES_RECEIVE_BOOKING_OPTIONS: "CLASSES_RECEIVE_BOOKING_OPTIONS",
    CLASSES_SET_BOOKING_OPTIONS_LOADED: "CLASSES_SET_BOOKING_OPTIONS_LOADED",
    CLASSES_SET_BOOKING_OPTIONS_LOADING: "CLASSES_SET_BOOKING_OPTIONS_LOADING",
    CLASSES_REQUEST_CLASSES_CUSTOMER: "CLASSES_REQUEST_CLASSES_CUSTOMER",
    CLASSES_RECEIVE_CLASSES_CUSTOMER: "CLASSES_RECEIVE_CLASSES_CUSTOMER",
}

export default types