const types = {
    CHECKIN_REQUEST_CLASS_ATTENDANCE: "CHECKIN_REQUEST_CLASS_ATTENDANCE",
    CHECKIN_RECEIVE_CLASS_ATTENDANCE: "CHECKIN_RECEIVE_CLASS_ATTENDANCE",
    CHECKIN_SET_CLASS_ATTENDANCE_LOADED: "CHECKIN_SET_CLASS_ATTENDANCE_LOADED",
    CHECKIN_SET_CLASS_ATTENDANCE_LOADING: "CHECKIN_SET_CLASS_ATTENDANCE_LOADING",
    CHECKIN_SET_CLASS_ATTENDANCE_SEARCH_CUSTOMER_ID: "CHECKIN_SET_CLASS_ATTENDANACE_SEARCH_CUSTOMER_ID"
}

export default types