const types = {
    CHECKIN_REQUEST_CLASSES: "CHECKIN_REQUEST_CLASSES",
    CHECKIN_RECEIVE_CLASSES: "CHECKIN_RECEIVE_CLASSES",
    CHECKIN_SET_CLASSES_LOADED: "CHECKIN_SET_CLASSES_LOADED",
    CHECKIN_SET_CLASSES_LOADING: "CHECKIN_SET_CLASSES_LOADING",
}

export default types