const types = {
    CLEAR_CUSTOMER_SCHOOL_INFO: "CLEAR_CUSTOMER_SCHOOL_INFO",
    REQUEST_CUSTOMER_SCHOOL_INFO: "REQUEST_CUSTOMER_SCHOOL_INFO",
    RECEIVE_CUSTOMER_SCHOOL_INFO: "RECEIVE_CUSTOMER_SCHOOL_INFO",
}

export default types