const types = {
    REQUEST_USER: "REQUEST_USER",
    RECEIVE_USER: "RECEIVE_USER",
    SET_ERROR: "SET_ERROR",
    SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
    SET_ERROR_DATA: "SET_ERROR_DATA",
    SET_LOADED: "SET_LOADED",
    SET_LOADING: "SET_LOADING",
    SET_LOADING_MESSAGE: "SET_LOADING_MESSAGE",
    SET_LOADING_PROGRESS: "SET_LOADING_PROGRESS",
    SET_LOCALE: "SET_LOCALE",
    SET_PAGE_TITLE: "SET_PAGE_TITLE"
}

export default types