const types = {
    REQUEST_PAYMENT_METHODS: "REQUEST_PAYMENT_METHODS",
    RECEIVE_PAYMENT_METHODS: "RECEIVE_PAYMENT_METHODS",
    REQUEST_USER: "REQUEST_USER",
    RECEIVE_USER: "RECEIVE_USER",
    REQUEST_SETTINGS: "REQUEST_SETTINGS",
    RECEIVE_SETTINGS: "RECEIVE_SETTINGS",
    SET_ERROR: "SET_ERROR",
    SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
    SET_ERROR_DATA: "SET_ERROR_DATA",
    SET_LOADED: "SET_LOADED",
    SET_LOADING: "SET_LOADING",
    SET_LOADING_MESSAGE: "SET_LOADING_MESSAGE",
    SET_LOADING_PROGRESS: "SET_LOADING_PROGRESS",
    SET_LOCALE: "SET_LOCALE",
    SET_PAGE_TITLE: "SET_PAGE_TITLE",
    REQUEST_SUBMIT_CART: "REQUEST_SUBMIT_CART",
    RECEIVE_SUBMIT_CART: "RECEIVE_SUBMIT_CART",
}

export default types