const types = {
    SET_LOADED: "SET_LOADED",
    SET_LOADING: "SET_LOADING",
    SET_LOADING_MESSAGE: "SET_LOADING_MESSAGE",
    SET_LOADING_PROGRESS: "SET_LOADING_PROGRESS",
    SET_LOCALE: "SET_LOCALE",
    SET_PAGE_TITLE: "SET_PAGE_TITLE"
}

export default types