const types = {
    CHECKIN_REQUEST_BOOKING_OPTIONS: "CHECKIN_REQUEST_BOOKING_OPTIONS",
    CHECKIN_RECEIVE_BOOKING_OPTIONS: "CHECKIN_RECEIVE_BOOKING_OPTIONS",
    CHECKIN_SET_BOOKING_OPTIONS_LOADED: "CHECKIN_SET_BOOKING_OPTIONS_LOADED",
    CHECKIN_SET_BOOKING_OPTIONS_LOADING: "CHECKIN_SET_BOOKING_OPTIONS_LOADING",
    CHECKIN_REQUEST_CLASS_CHECKIN: "CHECKIN_REQUEST_CLASS_CHECKIN",
    CHECKIN_RECEIVE_CLASS_CHECKIN: "CHECKIN_RECEIVE_CLASS_CHECKIN",
}

export default types