const types = {
    CHECKIN_REQUEST_BOOKING_OPTIONS: "CHECKIN_REQUEST_BOOKING_OPTIONS",
    CHECKIN_RECEIVE_BOOKING_OPTIONS: "CHECKIN_RECEIVE_BOOKING_OPTIONS",
    CHECKIN_SET_BOOKING_OPTIONS_LOADED: "CHECKIN_SET_BOOKING_OPTIONS_LOADED",
    CHECKIN_SET_BOOKING_OPTIONS_LOADING: "CHECKIN_SET_BOOKING_OPTIONS_LOADING",
    CHECKIN_REQUEST_CHECKIN_CUSTOMER: "CHECKIN_REQUEST_CHECKIN_CUSTOMER",
    CHECKIN_RECEIVE_CHECKIN_CUSTOMER: "CHECKIN_RECEIVE_CHECKIN_CUSTOMER",
}

export default types