const types = {
    REQUEST_PRODUCTS: "REQUEST_PRODUCTS",
    RECEIVE_PRODUCTS: "RECEIVE_PRODUCTS",
    REQUEST_PRODUCT_CATEGORIES: "REQUEST_PRODUCT_CATEGORIES",
    RECEIVE_PRODUCT_CATEGORIES: "RECEIVE_PRODUCT_CATEGORIES",
    SET_SEARCH_TIMEOUT: "SET_SEARCH_TIMEOUT",
    CLEAR_SEARCH_TIMEOUT: "CLEAR_SEARCH_TIMEOUT",
    SET_SEARCH_PRODUCT_ID: "SET_SEARCH_PRODUCT_ID",
    CLEAR_SEARCH_PRODUCT_ID: "CLEAR_SEARCH_PRODUCT_ID",
    CLEAR_SEARCH_VALUE: "CLEAR_SEARCH_VALUE",
    SET_SEARCH_VALUE: "SET_SEARCH_VALUE",
    SET_CATEGORY_FILTER_ID: "SET_CATEGORY_FILTER_ID",
    CLEAR_CATEGORY_FILTER_ID: "CLEAR_CATEGORY_FILTER_ID",
}

export default types